# Generated by Django 5.0.6 on 2024-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crausallink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idunique', models.IntegerField()),
                ('crausal1', models.CharField(max_length=200)),
                ('crausal2', models.CharField(max_length=200)),
                ('crausal3', models.CharField(max_length=200)),
                ('crausal4', models.CharField(max_length=200)),
                ('crausal5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('mail', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=20)),
                ('rpass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.IntegerField()),
                ('movieimagelink', models.CharField(max_length=30)),
                ('moviename', models.CharField(max_length=40)),
                ('moviedate', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
                ('actors', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=10)),
                ('hindi', models.CharField(max_length=10)),
                ('south', models.CharField(max_length=10)),
                ('marathi', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('comedy', models.CharField(max_length=10)),
                ('drama', models.CharField(max_length=10)),
                ('advanture', models.CharField(max_length=10)),
                ('romantic', models.CharField(max_length=10)),
                ('link1', models.CharField(max_length=10)),
                ('link2', models.CharField(max_length=10)),
                ('link4', models.CharField(max_length=10)),
            ],
        ),
    ]
