# Generated by Django 5.0.6 on 2024-07-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_link1_alter_movie_link2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.IntegerField()),
                ('code2', models.IntegerField()),
                ('code3', models.IntegerField()),
                ('code4', models.IntegerField()),
            ],
        ),
    ]
