# Generated by Django 5.0.6 on 2024-07-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code1', models.IntegerField()),
                ('code2', models.IntegerField()),
                ('code3', models.IntegerField()),
                ('code4', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
        ),
    ]
